FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./

COPY ./certificate/ ./

COPY ./libs/ ./libs

RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "-u", "./main.py" ]
#CMD [ "echo", "Hello===" ]