FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY ./certificate/ ./

RUN pip install ptvsd==4.1.3

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "-u", "./main.py" ]
#CMD [ "echo", "Hello===" ]